export const GET_EMPLOYEES = '[EMPLOYEE] GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = '[EMPLOYEE] GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = '[EMPLOYEE] GET_EMPLOYEES_ERROR';

export const ADD_EMPLOYEE = '[EMPLOYEE] ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = '[EMPLOYEE] ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = '[EMPLOYEE] ADD_EMPLOYEE_ERROR';

export const UPDATE_EMPLOYEE = '[EMPLOYEE] UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = '[EMPLOYEE] UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = '[EMPLOYEE] UPDATE_EMPLOYEE_ERROR';

export const DELETE_EMPLOYEE = '[EMPLOYEE] DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = '[EMPLOYEE] DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = '[EMPLOYEE] DELETE_EMPLOYEE_ERROR';